config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :workouts do
    member do
      get :start
    end
    resources :rounds
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :rounds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update]
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  def index
    @workout = Workout.find(params[:workout_id])
    @rounds = Round.where(workout_id: @workout.id)
  end

  def show
  end

  def new
    @workout = Workout.find(params[:workout_id])
    @round = Round.new
  end

  def create
    @workout = Workout.find(params[:workout_id])
    @round = Round.new(round_params)
    @round.workout_id = @workout.id
    if @round.save!
      redirect_to workout_round_path(params[:workout_id], @round.id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @round.update(round_params)
      redirect_to workout_round_path(params[:workout_id], @round.id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @round.destroy
    redirect_to workout_rounds_path(params[:workout_id]), status: :see_other
  end

  private

  def round_params
    params.require(:round).permit(:combo, :work_time, :rest_time)
  end

  def set_workout
    @workout = Workout.find(params[:workout_id])
  end

  def set_round
    @round = Round.find(params[:id])
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy, :start]

  def index
    @workouts = Workout.all
  end

  def show
  end

  def start
    @rounds = Round.where(workout_id: @workout.id)
    respond_to do |format|
      format.html
      format.json { render json: @rounds }
    end
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save!
      redirect_to workout_path(@workout.id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to workout_path(@workout.id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @workout.destroy
    redirect_to workouts_path, status: :see_other
  end

  private

  def workout_params
    params.require(:workout).permit(:name)
  end

  def set_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoxingTimer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Karantina&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rounds/_round_form.html.erb
<%= form_with model: [@workout, @round] do |f| %>
  <%= f.label :combo %>
  <%= f.text_field :combo %>
  <%= f.label :work_time %>
  <%= f.number_field :work_time %>
  <%= f.label :rest_time %>
  <%= f.number_field :rest_time %>
  <%= f.submit %>
<% end %>

app/views/rounds/edit.html.erb
<h2>Edit Round</h2>
<%= render "round_form", round: [@workout, @round] %>
<p> <%= link_to "Back", workout_rounds_path(params[:workout_id], params[:id]) %> </p>

app/views/rounds/index.html.erb
<h2>All Workouts</h2>
<p> <%= link_to "New Timer", new_workout_round_path(params[:workout_id]) %> </p>
<% @rounds.each do |round| %>
  <p> <%= link_to round.combo, workout_round_path(params[:workout_id], round.id) %> </p>
<% end %>
<p> <%= link_to "Back", workouts_path %> </p>

app/views/rounds/new.html.erb
<h2>New Round</h2>
<%= render "round_form", round: [@workout, @round] %>
<p> <%= link_to "Back", workout_rounds_path(params[:workout_id]) %> </p>

app/views/rounds/show.html.erb
<h2> <%= @round.combo %> </h2>
<p> <%= link_to "Back", workout_rounds_path(params[:workout_id]) %> </p>
<p> <%= link_to "Edit", edit_workout_round_path(params[:workout_id], params[:id]) %> </p>
<p> <%= link_to "Delete", workout_round_path(params[:workout_id], params[:id]), data: {turbo_method: :delete, confirm: "Are you sure?"} %> </p>

app/views/workouts/_workout_form.html.erb
<%= form_with model: @workout do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/workouts/edit.html.erb
<h2>Edit Workout</h2>
<%= render "workout_form", workout: @workout %>
<p> <%= link_to "Back", workout_path(@workout.id) %> </p>

app/views/workouts/index.html.erb
<h2>All Workouts</h2>
<p> <%= link_to "New", new_workout_path %> </p>
<% @workouts.each do |workout| %>
  <p> <%= link_to workout.name, workout_path(workout.id) %> </p>
<% end %>

app/views/workouts/new.html.erb
<h2>New Workout</h2>
<%= render "workout_form", workout: @workout %>
<p> <%= link_to "Back", workouts_path %> </p>

app/views/workouts/show.html.erb
<h2> <%= @workout.name %> </h2>
<p> <%= link_to "Index", workouts_path %> </p>
<p> <%= link_to "Timers", workout_rounds_path(@workout.id) %> </p>
<p> <%= link_to "Edit", edit_workout_path(@workout.id) %> </p>
<p> <%= link_to "Delete", workout_path(@workout.id), data: {turbo_method: :delete, confirm: "Are you sure?"} %> </p>

app/views/workouts/start.html.erb
<div><p id="round-hidden" class="hide"> </p></div>
<div class="center-x center-text" > <p id="title" class="font-64 text-hover-red"> COMBO COUNTER </p></div>
<div class="center-x center-text">
  <div class="flex flex-column">

    <div><p id="round" class="font-56"> Round 1 </p></div>
    <div><p id="phase" class="secondary-text font-32"> -- </p></div>

    <div><p id="round-time" class="secondary-text font-32"> <%= @rounds[0].work_time %> </p></div>
    <div><p id="timer" class="font-56"> <%= @rounds[0].work_time %> </p></div>
    <div><p id="progress" class="secondary-text font-32"> -- </p></div>

    <div class="border-faint">
      <div class="progress progress-red" id="progressBar"></div>
    </div>

    <div><p id="combo" class="font-48"> <%= @rounds[0].combo %> </p></div>

    <div class="flex-row">
      <button id="start" type="button">Start!</button>
      <button id="pause" type="button" class="hide">Pause!</button>
      <button id="resume" type="button" class="hide">Resume!</button>
      <button id="reset" type="button" class="hide">Reset!</button>
      <button id="reset-all" type="button" class="hide">Restart!</button>
      <button id="reset-workout" type="button" class="hide">Reset Workout!</button>
    </div>
  </div>
</div>

<script>
const allRounds = <%= raw @rounds.to_json %>;
const title = document.querySelector("#title");
const roundDisplay = document.querySelector("#round");
const roundIndexHidden = document.querySelector("#round-hidden");
const timerDisplay = document.querySelector("#timer");
const phaseDisplay = document.querySelector("#phase");
const comboDisplay = document.querySelector("#combo");
const progressDisplay = document.querySelector("#progress");

const startButton = document.querySelector("#start");
const pauseButton = document.querySelector("#pause");
const resumeButton = document.querySelector("#resume");
const resetButton = document.querySelector("#reset");
const resetAllButton = document.querySelector("#reset-all");
const resetWorkoutButton = document.querySelector("#reset-workout");

</script>


<script>



function colourBlue() {
  progressBar.classList.remove("progress-red")
  title.classList.remove("text-hover-red")
  progressBar.classList.add("progress-blue")
  title.classList.add("text-hover-blue")
}
function colourRed() {
  progressBar.classList.add("progress-red")
  title.classList.add("text-hover-red")
  progressBar.classList.remove("progress-blue")
  title.classList.remove("text-hover-blue")
}

function toggleButtons() {
  resetAllButton.classList.toggle("hide")
  resetButton.classList.toggle("hide")
  pauseButton.classList.toggle("hide")
  resumeButton.classList.toggle("hide")
};

pauseButton.addEventListener("click", (event) => {
      toggleButtons()
  });

function runRound(roundIndex, phase, countStart) {
  const round = allRounds[roundIndex];
  const comboSpeech = new SpeechSynthesisUtterance();
  const restSpeech = new SpeechSynthesisUtterance();
  const finishSpeech = new SpeechSynthesisUtterance();

  function updateProgress(newValue) {
    progressBar.value = newValue;
    progressBar.getElementsById('progressBarSpan')[0].textContent = newValue;
  }

  console.log(round);
  console.log(roundIndex)

  countStart === 0 ? (count = ((phase === 'work') ? round.work_time * 100 : round.rest_time * 100)) : count = countStart;

  finishSpeech.text = "Workout Complete!"
  restSpeech.text = "rest"
  comboSpeech.text = `${round.combo}`;
  phase === "work" ? window.speechSynthesis.speak(comboSpeech) : window.speechSynthesis.speak(restSpeech);

  let timer = setInterval(function() {

    let progress = (phase === 'work') ? (count / round.work_time).toFixed(1) : (count / round.rest_time).toFixed(1);
    const progressBar = document.getElementById('progressBar');

    (phase === 'work') ? colourRed() : colourBlue();

    count--;
    roundDisplay.innerText = `Round ${roundIndex + 1}`;
    roundIndexHidden.innerText = roundIndex;
    comboDisplay.innerText = round.combo;
    phaseDisplay.innerText = phase;
    timerDisplay.innerText = (count / 100).toFixed(1);
    progressDisplay.innerText = `${progress}%`;
    progressBar.style.width = `${progress}%`;



    if (count === 0) {
      clearInterval(timer);
      console.log(`Time's up for ${phase} phase!`);
      console.log(round)
      console.log(round.work_time)
      console.log(roundIndex)
      console.log(typeof roundIndex)

      // Move to the next phase or round if available
      if (phase === 'work') {
        if (roundIndex !== allRounds.length - 1) {
          setTimeout(() => runRound(roundIndex, 'rest', 0), 10); // Start resting after 1000ms (adjust as needed)
        } else if (roundIndex === allRounds.length - 1) {
          console.log("FINISHED")
          window.speechSynthesis.speak(finishSpeech)
          phaseDisplay.innerText = "workout complete";
          progressDisplay.innerText = "0%";
          pauseButton.classList.toggle("hide")
          resetWorkoutButton.classList.toggle("hide")
        }
      } else {
        if (roundIndex < allRounds.length - 1) {
          setTimeout(() => runRound(roundIndex + 1, 'work', 0), 10); // Start working after 1000ms (adjust as needed)
        }
      }
    }

  pauseButton.addEventListener("click", (event) => {
      clearInterval(timer);
  });

  }, 10);

}

resumeButton.addEventListener("click", (event) => {
  console.log("clicked");

  // need something to reset!

  let roundStart = parseInt(document.querySelector("#round-hidden").innerText);
  let phaseStart = document.querySelector("#phase").innerText;
  let countStart = document.querySelector("#timer").innerText * 100;

  toggleButtons()

  runRound(roundStart, phaseStart, countStart);


  console.log(roundStart);
  console.log(phaseStart);
  console.log(countStart);

  console.log("resuming");
});

startButton.addEventListener("click", (event) => {
  console.log("clicked");
  runRound(0, 'work', 0);
  startButton.classList.toggle("hide")
  pauseButton.classList.toggle("hide")
  console.log("done");
});

resetButton.addEventListener("click", (event) => {
  toggleButtons()

  let roundStart = parseInt(document.querySelector("#round-hidden").innerText);
  let phaseStart = document.querySelector("#phase").innerText;

  roundDisplay.innerText = `Round ${roundStart + 1}`;

  runRound(roundStart, "work", 0);
  console.log("done");
});

resetAllButton.addEventListener("click", (event) => {
  toggleButtons()
  runRound(0, 'work', 0);
  console.log("done");
});

resetWorkoutButton.addEventListener("click", (event) => {
  pauseButton.classList.toggle("hide")
  resetWorkoutButton.classList.toggle("hide")
  runRound(0, 'work', 0);
  console.log("done");
});


</script>
          <%# const comboNames = new Array() %>

      <%# <% @rounds.each do |round| %>
        <%# comboNames.push( <%= round.combo %>
      <%# <% end %>